### ISSUE TITLE
dd/timed - java.io.IOException: Operation not permitted (sendto failed)

### ISSUE THREAD

**Issue by kwladyka** [truckerpath/clj-datadog#10]
```
java.io.IOException: Operation not permitted (sendto failed)
    at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at truckerpath.clj_datadog.core$send_msg.invokeStatic(core.clj:38)
    at truckerpath.clj_datadog.core$send_msg.invoke(core.clj:33)
    at truckerpath.clj_datadog.core$timing.invokeStatic(core.clj:93)
    at truckerpath.clj_datadog.core$timing.invoke(core.clj:81)
```

It happens when use`dd/timed` with async. Exactly when more than 1 thread want use it.

**Comment by kwladyka** [comment]
I guess it is because of https://github.com/truckerpath/clj-datadog/blob/master/src/truckerpath/clj_datadog/core.clj#L31

It should be queued probably or new socket should be create each time. Not sure about performance.

**Comment by mikekap** [comment]
This is actually due to a known behavior in the linux kernel when sending UDP packets too fast. See https://github.com/netty/netty/issues/1258 for a similar issue. https://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted also has a solution that might work.

This CAN be fixed via a new socket every time, but that can easily lead to FD exhaustion (which is what I was seeing before), if you're e.g. using docker which forwards UDP packets in userspace. We could probably use a socket per thread - wdyt?

**Comment by kwladyka** [comment]
Hmm could be. Do you think is it possible to implement that logic into macro `dd/timed`? Just to not force people to add lines to create sockets in each thread and pass the socket deeper. Maybe get thread id and using this value to recognise thread. If socket not created before, create it now. If create use it. Only problem when thread end to remove socket. Not sure how to solve it.

**Comment by kwladyka** [comment]
Actually after rethinking it "during sleep" ;) it is probably not the right solution, because potentially people can use it with *many* threads with I/O operations. It could bring new issues, because as you mentioned:
>  that can easily lead to FD exhaustion

So probably the right solution is to make non-blocking queue based on `atom` or `agent` or something else.

BTW In such case it would be even possible to send array of queued data at once if it is possible in datadog API to improve performance.

**Comment by kwladyka** [comment]
Hi, did you think about solution @mikekap ?

**Comment by mikekap** [comment]
I think the completely right solution might be a dynamically scaling worker pool where each of the threads in the pool has a socket it writes to. That said, I think that's overkill - for my purposes a socket per thread works fine - the number of threads is fairly bounded. It's what I implemented in https://github.com/truckerpath/clj-datadog/pull/11/files
